# Generated by Django 5.1.4 on 2025-03-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_club_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
