# Generated by Django 5.1.4 on 2025-03-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_user_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='email',
            field=models.EmailField(blank=True, default='contact@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='club',
            name='website',
            field=models.URLField(blank=True, default='https://gymkhana.iiti.ac.in/'),
        ),
    ]
