# Generated by Django 5.1.4 on 2025-03-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_project_image_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='council_heads/')),
            ],
        ),
    ]
