# Generated by Django 5.1.4 on 2025-03-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myevents', '0002_event_contact_event_fees_event_register_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='event_pdfs/'),
        ),
    ]
