# Generated by Django 5.0.3 on 2025-03-16 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.EmailField(default='info@iitindore.ac.in', max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='fees',
            field=models.CharField(default='Free Entry', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='register_link',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.CharField(default='TBD', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.URLField(default='/data/media/images/general/dummy.jpg'),
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='events.event')),
            ],
        ),
    ]
