# Generated by Django 5.0.3 on 2025-03-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_contact_event_fees_event_register_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(default='event_posters/default.jpg', upload_to='event_posters/'),
        ),
    ]
