# Generated by Django 5.0.3 on 2025-03-20 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='events.event'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='events.event'),
        ),
    ]
