# Generated by Django 5.0.3 on 2025-03-21 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_agenda_event_alter_speaker_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='events.event'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='events.event'),
        ),
    ]
