# Generated by Django 5.1.4 on 2025-03-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_agenda_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
