# Generated by Django 5.0.3 on 2025-03-24 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_agenda_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speaker',
            options={},
        ),
        migrations.CreateModel(
            name='EventInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_allocated', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('budget_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItemEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumable', models.CharField(choices=[('consumable', 'Consumable'), ('non_consumable', 'Non-Consumable')], max_length=15)),
                ('event_inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='events.eventinventory')),
            ],
        ),
    ]
