# Generated by Django 5.1.4 on 2025-03-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_election_position_candidate_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='manifesto',
        ),
        migrations.AddField(
            model_name='candidate',
            name='branch',
            field=models.CharField(default='CSE', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='department',
            field=models.CharField(default='Computer Science and Engineering', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='roll_no',
            field=models.CharField(default='Unknown Roll No', max_length=50),
        ),
    ]
