# Generated by Django 5.1.4 on 2025-03-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_remove_candidate_bio_remove_candidate_manifesto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='department',
        ),
        migrations.AddField(
            model_name='candidate',
            name='degree',
            field=models.CharField(choices=[('BTech', 'BTech'), ('MTech', 'MTech'), ('PhD', 'PhD')], default='BTech', max_length=10),
        ),
    ]
