# Generated by Django 5.1.4 on 2025-03-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_remove_candidate_branch_remove_candidate_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='branch',
            field=models.CharField(default='CSE', max_length=100),
        ),
    ]
