# Generated by Django 5.1.4 on 2025-03-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_position_batch_restriction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='batch_restriction',
        ),
        migrations.RemoveField(
            model_name='position',
            name='branch_restriction',
        ),
    ]
