# Generated by Django 5.1.4 on 2025-03-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_remove_position_batch_restriction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='batch_restriction',
            field=models.JSONField(default=list, help_text='List of eligible batches that can vote.'),
        ),
        migrations.AddField(
            model_name='position',
            name='branch_restriction',
            field=models.JSONField(default=list, help_text='List of eligible branches that can vote.'),
        ),
    ]
