# Generated by Django 5.1.4 on 2025-03-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_position_batch_restriction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='max_candidates',
        ),
        migrations.RemoveField(
            model_name='position',
            name='max_votes_per_voter',
        ),
    ]
