# Generated by Django 5.1.4 on 2025-03-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_remove_position_max_candidates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='voter_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='degree',
            field=models.CharField(choices=[('BTech', 'BTech'), ('MTech', 'MTech'), ('PHD', 'PHD'), ('MSC', 'MSC')], default='BTech', max_length=10),
        ),
    ]
