# Generated by Django 5.0.3 on 2025-03-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_remove_position_max_candidates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='max_candidates',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='position',
            name='max_votes_per_voter',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
