# Generated by Django 5.1.4 on 2025-03-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_voterfile_alter_candidate_degree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='branch',
            new_name='Department',
        ),
    ]
