# Generated by Django 5.0.3 on 2025-03-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_rename_branch_candidate_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='branch_restriction',
            field=models.JSONField(default=list, help_text='List of eligible departments that can vote.'),
        ),
    ]
