# Generated by Django 5.1.4 on 2025-03-25 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_alter_position_branch_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterfile',
            name='election',
            field=models.ForeignKey(blank=True, help_text='The election this voter file is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voter_files', to='testapp.election'),
        ),
    ]
