# Generated by Django 5.0.3 on 2025-03-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_voterfile_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='degree_restriction',
            field=models.JSONField(default=list, help_text='List of eligible degrees that can vote.'),
        ),
    ]
